### ISSUE TITLE
Change contributors link in index.html to point to this repo

### ISSUE THREAD

**Issue by SeanKilleen** [joshuawalcher/writtenkitten#7]
Currently points to Skud's old repo.

Would have done this as a PR but I'm on mobile.

**Comment by joshuawalcher** [comment]
Can't really do that since Skud is a contributor and it's pointing not to the old WK repo but to her actual page on Github. I could switch it to point to her Twitter, but her Twitter account is hidden unless she approves you. As such, I think it's probably best to leave it as-is unless you have a better idea?

**Comment by SeanKilleen** [comment]
Hey @joshuawalcher! Sorry, I don't think I articulated clearly.

I'm proposing changing the link on the home page that says "and contributors", because it points to the old contributors page on the old repo. Pointing to the contributors page in the new repo, we can keep the original authors' credits but include new contributors as they emerge. 

I definitely wouldn't want to change links to the direct pages on the site -- just to the reference to contributors.md since we'll obviously honor the original folks there too.

**Comment by SeanKilleen** [comment]
Specifically, I'm proposing changing the link from https://github.com/Skud/writtenkitten/blob/master/CONTRIBUTORS.md

To;

https://github.com/joshuawalcher/writtenkitten/blob/master/CONTRIBUTORS.md

**Comment by joshuawalcher** [comment]
Ah, sorry. I misunderstood. I'll get that fixed. Thanks!
